### ISSUE TITLE
SMTP Standard-Port, Auswahl Zusatz-Optionen Archiv/Log

### ISSUE THREAD

**Issue by skerbis** [alexplusde/mailer_profile#1]
Sieht gut aus. 👍🏻 

- [ ] - Ich glaube die **Versandeinstellungen** und **Log** kannst du weglassen. Die fasst doch niemand wirklich an. Das kann doch zentral bleiben
- [x] - Beim Port für den SMTP würde ich 587 vorgeben

**Comment by alxndr-w** [comment]
Oder was hältst du hiervon? @skerbis 

![image](https://user-images.githubusercontent.com/3855487/163403813-5fc09da4-4c0f-497b-a4c3-cdd3cf4093d3.png)

Ne, stimmt schon. Ich nehm's mit auf.

(D.h. alles andere funktioniert wie gewünscht?)

**Comment by alxndr-w** [comment]
Standard-Port ist gesetzt. Wegen der Archiv- und Log-Einstellungen bin ich mir noch unschlüssig. Man kann das ja durchaus auch im Live-Betrieb einsetzen, um bspw. kurz über ein anderes Versandprofil zu gehen und die Infos loggen zu lassen, während normale Nutzer und andere YForm-Formulare davon nichts mitbekommen.

**Comment by skerbis** [comment]
Jogging sehe ich auch in den Haupteinstellungen
