### ISSUE TITLE
Falsche Funktionsaufrufe in setProfile?

### ISSUE THREAD

**Issue by maxsmily** [alexplusde/mailer_profile#11]
Um das Addon nutzen zu können, musste ich in mailer_profile in der Funktion setProfile folgende Aufrufe ändern:

$mailer->ConfirmReadingTo = $profile->getConfirmto(); // statt $profile->getConfirmReadingTo();
$mailer->SMTPAutoTLS = $profile->getSecurityMode(); // statt $profile->getSMTPAutoTLS();

Grüße
Daniel

**Comment by alxndr-w** [comment]
@maxsmily möchtest du mir das als Pull Request vorbereiten?

Ich forsche indes mal nach.

**Comment by alxndr-w** [comment]
Es müsste umgekehrt sein, ich habe aus Versehen die Methodennamen geändert.

**Comment by alxndr-w** [comment]
@maxsmily machst du einen PR?

**Comment by alxndr-w** [comment]
Merci!
